name: boundary-conditions-for-pinos
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - contourpy=1.3.1=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.55.3=py311h827c3e9_0
  - freeglut=3.4.0=hd77b12b_0
  - freetype=2.13.3=h0620614_0
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h827c3e9_3
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.0=py311haa95532_0
  - matplotlib-base=3.10.0=py311he19b0ae_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - numpy=2.2.4=py311hb0d8612_0
  - numpy-base=2.2.4=py311h557a8af_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.16=h3f729d1_0
  - packaging=24.2=py311haa95532_0
  - pillow=11.1.0=py311hea0d53e_1
  - pip=25.1=pyhc872135_2
  - pyparsing=3.2.0=py311haa95532_0
  - pyqt=6.7.1=py311h5da7b33_1
  - pyqt6-sip=13.9.1=py311h827c3e9_1
  - python=3.11.11=h4607a30_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - qtbase=6.7.3=h0804d20_0
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - setuptools=72.1.0=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py311h827c3e9_0
  - typing=3.10.0.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - vc=14.42=haa95532_5
  - vs2015_runtime=14.42.34433=hbfb602d_5
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - sympy==1.13.3
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - typing-extensions==4.12.2
prefix: D:\anaconda3\envs\boundary-conditions-for-pinos
